# Defines the application-level services.
# This file depends on the infrastructure being started first.
version: '3.8'

services:
  service-a:
    image: ghcr.io/wingorithm/fastapi-microservice-template/service-a:release-dev
    container_name: service-a
    ports:
      - "8081:8081"
    environment:
      - SERVICE_NAME=service-a
      - ENVIRONMENT=DEV
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
    networks:
      - microservices-net

  service-b:
    image: ghcr.io/wingorithm/fastapi-microservice-template/service-b:release-dev
    container_name: service-b
    ports:
      - "8082:8082"
    environment:
      - SERVICE_NAME=service-b
      - ENVIRONMENT=DEV
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
    networks:
      - microservices-net

networks:
  microservices-net:
    external: true